const std::string InternalShaders::colorFragmentShader =
"struct Material\n"
"{\n"
"   vec4 color;\n"
"};\n"
"uniform Material material;\n"
"out vec4 FragColor;\n"
"void main()\n"
"{\n"
"#if defined(DIRECTIONALLIGHT)\n"
"#if defined(SOFTSHADOWS) || defined(HARDSHADOWS)\n"
"	FragColor = material.color;\n"
"#endif\n"
"#else\n"
"	FragColor = material.color;\n"
"#endif\n"
"}\n";