const std::string InternalShaders::shadowDepthCubemapGeometryShader =
"layout (triangles) in;\n"
"layout (triangle_strip, max_vertices=18) out;\n"
"uniform mat4 cubeViewProjMatrices[6];\n"
"out vec4 FragPos;\n"
"void main()\n"
"{\n"
"	for(int i = 0; i < 6; i++){\n"
"		gl_Layer = i;\n"
"		for(int j = 0; j < 3; j++){\n"
"			FragPos = gl_in[j].gl_Position;\n"
"			gl_Position = cubeViewProjMatrices[i] * FragPos;\n"
"			EmitVertex();\n"
"		}\n"
"		EndPrimitive();\n"
"	}\n"
"}\n";